# Enable ZMK pointing device support (mouse keys, scroll, etc.)
CONFIG_ZMK_POINTING=y

## Prospector Scanner config
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="Totem"
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"
CONFIG_PROSPECTOR_EXPECTED_PERIPHERAL_COUNT=1

## Report battery status
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y