# Enable ZMK pointing device support (mouse keys, scroll, etc.)
CONFIG_ZMK_POINTING=y

## Prospector Scanner config
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="Totem"
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"
CONFIG_PROSPECTOR_EXPECTED_PERIPHERAL_COUNT=1

## Report battery status for both halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Soft off
CONFIG_ZMK_PM_SOFT_OFF=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# Go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
