manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: willACosta
      url-base: https://github.com/WillACosta

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: willACosta
      remote: prospector
      revision: main
      path: modules/prospector-zmk-module

    - name: zmk-rgbled-widget
      remote: willACosta
      revision: main
      path: modules/zmk-rgbled-widget

  self:
    path: config
